/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javamodules.app;

import java.util.Arrays;
import static javamodules.utilities.JoinUtils.join;

public class App {
    public static void main(String[] args) {
        var list = Arrays.asList("Hello", "World");
        System.out.println(join(list));
    }
}
